engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "server/*.js"
  - "server/**/*.js"
exclude_paths:
- node_modules/
- server/database/migrations
- server/database/config
- server/tests/
- client
- coverage
- production
- tools