import keymirror from 'keymirror';

export default keymirror({
  SIGNUP_SUCCESSFUL: null,
  SIGNUP_UNSUCCESSFUL: null,
  SIGNUP_VALIDATION_ERROR: null,
  CANCEL_MODAL: null,
  SIGNIN_SUCCESSFUL: null,
  SIGNIN_UNSUCCESSFUL: null,
  SIGNIN_VALIDATION_ERROR: null,
  VERIFY_TOKEN: null,
  GROUP_CREATE_SUCCESSFUL: null,
  GROUP_CREATE_ERROR: null,
  GROUP_ADD_USER_SUCCESSFUL: null,
  GROUP_ADD_USER_ERROR: null,
  CLEAR_ADD_USER_TO_GROUP_ERROR: null,
  POST_MESSAGE_SUCCESSFUL: null,
  POST_MESSAGE_ERROR: null,
  CLEAR_POST_MESSAGE_ERROR: null
});
